# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

  # zephyr-keep-sorted-stop

manifest:
  version: "1.2"

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: 9d15e5b0476a7ab01277a720249d36bad8ef5ffb
      import:
        name-allowlist:
        - cmsis
        - cmsis-dsp
        - cmsis-nn
        - cmsis_6
        - hal_stm32
        - mcuboot
        - mipi-sys-t
        - picolibc
        - trusted-firmware-m
        - segger
    - name: zenoh-pico
      url: https://github.com/soburi/zenoh-pico.git
      revision: zephyr-update-1.10.0
      path: modules/lib/zenoh-pico # adjust the path as needed

  self:
    path: .
